# Generated by Django 5.2 on 2025-04-19 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customtokenmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomTokenModel',
        ),
    ]
